### ISSUE TITLE
Can I bug you?I  have a problem,Can you help?

### ISSUE THREAD

**Issue by javonLim** [LewisOrton/Houdini_Scripts#3]
when I drag and drop files to houdini,The system prompts an error message:
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
ImportError: cannot import name 'unquote' from 'urllib' (C:\PROGRA~1\SIDEEF~1\HOUDIN~1.383\python37\lib\urllib\__init__.py)
I solved the problems ，Thanks for sharing such a great plugin！

**Comment by LewisOrton** [comment]
Hi, sorry that I was on vacation, would you please elaborate on the problem in detail? I will need to investigate further if it affects widely.

**Comment by WuCheng0912** [comment]
externaldragdrop.py line 7--->from urllib.parse import unquote
