### ISSUE TITLE
External Drag and Drop Does Not Work As Expected

### ISSUE THREAD

**Issue by bentraje** [LewisOrton/Houdini_Scripts#4]
Hi, 

I copied the script to user pref directory as per instructions. But when I drag a file, image etc on the proper context it gives me an invalid hip file header, which I'm guessing the script is not registered.

Is there a specific procedure to enable the script? 

Like the following code:
```python
import module_name
module_name.module_method()
```

**Comment by LewisOrton** [comment]
There is no need to enable the script as long as it's copied to the proper folder.
Please elaborate on the issue, what path is your script in, and which version of Houdini are you working with.

**Comment by bentraje** [comment]
Hi Lewis,

Thanks for the response. Yea. I think its my bad. Haha. 
I was so sure yesterday of it not working. 

I did the exact same thing today but now it works. I guess my PC/Houdini just need a restart.
Sorry about that. Thanks again for sharing the script.

Have a great day ahead!
